DROP TABLE TASK CASCADE CONSTRAINTS;
DROP TABLE PROJECT CASCADE CONSTRAINTS;
DROP TABLE USERS CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_PROJECT;
DROP SEQUENCE SEQ_USER;
DROP SEQUENCE SEQ_TASK;

CREATE TABLE USERS (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    ROLE VARCHAR2(50) CHECK (ROLE IN ('Manager', 'Developer', 'Tester'))
);

CREATE TABLE PROJECT (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(150) NOT NULL,
    DESCRIPTION VARCHAR2(500),
    START_DATE DATE NOT NULL,
    END_DATE DATE
);

CREATE TABLE TASK (
    ID NUMBER PRIMARY KEY,
    TITLE VARCHAR2(150) NOT NULL,
    DESCRIPTION VARCHAR2(500),
    STATUS VARCHAR2(20) CHECK (STATUS IN ('Pending', 'In Progress', 'Completed')),
    PROJECT_ID NUMBER NOT NULL,
    ASSIGNED_USER_ID NUMBER,

    CONSTRAINT FK_TASK_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(ID),
    CONSTRAINT FK_TASK_USER FOREIGN KEY (ASSIGNED_USER_ID) REFERENCES USERS(ID)
);